language: go
go:
 - 1.x
 - tip

go_import_path: kmodules.xyz/security-policy-api

install: true

script:
  - go build ./...
  - ./hack/coverage.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
